---
broker:
  username: starkandwayne
  password: starkandwayne
  port: 3000
router:
  hostname: 54.221.66.11
backends:
- guid: "10.244.21.6"
  availability_zone: "z1"
  uri: "http://54.145.50.109:10006"
  username: "containers"
  password: "containers"
- guid: "10.244.21.7"
  availability_zone: "z1"
  uri: "http://54.145.50.109:10007"
  username: "containers"
  password: "containers"
- guid: "10.244.21.8"
  availability_zone: "z2"
  uri: "http://54.145.50.109:10008"
  username: "containers"
  password: "containers"

kvstore:
  type: etcd
  machines: ["http://54.221.66.11:14001"]
  username: ""
  password: ""

callbacks:
  provision_success: {cmd: tee, args: []}

catalog:
  services:
    - id: '0f5c1670-6dc3-11e5-bc08-6c4008a663f0'
      name: postgresql95
      description: 'PostgreSQL 9.5 service for application development and testing'
      bindable: true
      planupdateable: true
      tags: [postgresql95 postgresq]
      metadata:
        displayName: 'postgresql 9.5'
        longDescription: 'High-availablity cluster of PostgreSQL 9.5 running across multiple servers/availability zones'
        providerDisplayName: 'Dingo Tiles'
      plans:
        - id: '1545e30e-6dc3-11e5-826a-6c4008a663f0'
          name: 'cluster'
          description: 'High-availablity cluster of PostgreSQL'
          metadata: {displayName: 'Clustered'}
