---
broker:
  username: starkandwayne
  password: starkandwayne
  port: 3000
router:
  hostname: 54.82.6.219
backends:
- guid: "10.244.21.7"
  availability_zone: "z1"
  uri: "http://54.82.6.219:10217"
  username: "containers"
  password: "containers"
- guid: "10.244.22.2"
  availability_zone: "z2"
  uri: "http://54.82.6.219:10222"
  username: "containers"
  password: "containers"

kvstore:
  type: etcd
  machines: ["http://54.82.6.219:14001"]
  username: ""
  password: ""

callbacks:
  provision_success: {cmd: tee, args: []}

catalog:
  services:
    - id: beb5973c-e1b2-11e5-a736-c7c0b526363d
      name: postgresql95
      description: 'PostgreSQL 9.5 service for application development and testing'
      bindable: true
      planupdateable: true
      tags: [postgresql95 postgresq]
      metadata:
        displayName: 'postgresql 9.5'
        longDescription: 'High-availablity cluster of PostgreSQL 9.5 running across multiple servers/availability zones'
        providerDisplayName: 'Dingo Tiles'
        supportUrl: 'https://slack.dingotiles.com'
      plans:
        - id: b96d0936-e423-11e5-accb-93d374e93368
          name: cluster
          description: 'High-availablity cluster of PostgreSQL'
          metadata: {displayName: 'Clustered'}
