---
broker:
  username: starkandwayne
  password: starkandwayne
  port: 3000
router:
  hostname: 54.82.6.219
backends:
- guid: "10.244.21.7"
  availability_zone: "z1"
  uri: "http://54.82.6.219:10217"
  username: "containers"
  password: "containers"
- guid: "10.244.22.2"
  availability_zone: "z2"
  uri: "http://54.82.6.219:10222"
  username: "containers"
  password: "containers"

kvstore:
  type: etcd
  machines: ["http://54.82.6.219:14001"]
  username: ""
  password: ""

callbacks:
  clusterdata_backup: {cmd: jq, args: ["-r", "."]}
  clusterdata_restore: {cmd: echo, args: ['{"instance_id":"TESTID-1458690055","service_id":"beb5973c-e1b2-11e5-a736-c7c0b526363d","plan_id":"b96d0936-e423-11e5-accb-93d374e93368","organization_guid":"","space_guid":"","parameters":null,"node_count":1,"node_size":20,"allocated_port":"33000"}']}

catalog:
  services:
    - name: postgresql95
      id: beb5973c-e1b2-11e5-a736-c7c0b526363d
      description: 'PostgreSQL 9.5 service for application development and testing'
      bindable: true
      planupdateable: true
      tags: ["postgresql95", "postgresq"]
      metadata:
        displayname: displayname
        longdescription: 'High-availablity cluster of PostgreSQL 9.5 running across multiple servers/availability zones'
        providerdisplayname: 'Dingo Tiles'
        supporturl: 'https://slack.dingotiles.com'
      plans:
        - name: cluster
          id: b96d0936-e423-11e5-accb-93d374e93368
          description: 'High-availablity cluster of PostgreSQL'
          metadata:
            displayname: Clustered
            bullets:
            - PostgreSQL 9.5
            - Dedicated secure containers
            - Highly-available cluster across availability zones
            - Continuously archived for potential disaster recovery
