---
platform: linux
image: docker:///dingotiles/dingo-postgresql-release-pipeline

inputs:
- name: broker
  path: broker/src/github.com/dingotiles/patroni-broker

run:
  path: ./broker/src/github.com/dingotiles/patroni-broker/ci/scripts/build-and-test.sh
