---
groups:
- name: dingo-postgresql-broker
  jobs: [test-master, test-all]
- name: ci-image
  jobs: [build-task-image]

jobs:
- name: build-task-image
  serial: true
  plan:
    - {get: pipeline-ci-image, trigger: true}
    - put: docker-image-ci
      params:
        build: pipeline-ci-image/ci/ci_image
- name: test-master
  plan:
  - aggregate:
    - {get: broker, trigger: true}
    - get: broker-ci
  - task: run-tests
    file: broker-ci/ci/tasks/run-tests.yml

- name: test-all
  plan:
  - aggregate:
    - {get: broker-all, trigger: true}
  - task: run-tests-all
    file: broker-all/ci/tasks/run-tests-all.yml


resources:
- name: pipeline-ci-image
  type: git
  source:
    uri: https://github.com/dingotiles/dingo-postgresql-broker
    branch: {{pipeline-branch}}
    paths: [ci/ci_image/*]

- name: docker-image-ci
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: dingotiles/dingo-postgresql-broker-pipeline

- name: broker-ci
  type: git
  source:
    uri: https://github.com/dingotiles/dingo-postgresql-broker
    branch: {{pipeline-branch}}

- name: broker
  type: git
  source:
    uri: https://github.com/dingotiles/dingo-postgresql-broker
    branch: {{pipeline-branch}}

- name: broker-all
  type: git-multibranch
  source:
    uri: https://github.com/dingotiles/dingo-postgresql-broker
    branches: '.*'
    ignore_branches: 'master'


resource_types:
- name: git-multibranch
  type: docker-image
  source:
    repository: cfcommunity/git-multibranch-resource
